# Tensors

<div align="center">

<img src="https://user-images.githubusercontent.com/30636259/206873359-570aafd5-f906-4c63-a60c-b1ff62fd1775.png" width="800px"/>

</div>

### What is a tensor?
A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, PyTorch represents tensors as n-dimensional arrays. Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.

## Tensor creation

In [14]:
import torch

A = torch.randn((8,3,5))

print(A)

tensor([[[ 0.6891,  1.0174,  0.9346,  0.3579, -0.1727],
         [ 0.5856,  0.5580,  0.6725,  0.2370,  0.1169],
         [-0.5576,  0.5395,  1.2833,  1.7094,  0.6876]],

        [[-2.0420,  1.9101, -0.5104,  1.2429, -0.0421],
         [-1.3377, -0.2533, -1.5394, -0.8681,  0.5586],
         [ 1.0478, -0.8631, -1.2062, -1.0321,  0.0848]],

        [[-0.6572, -1.0172, -1.6541, -0.4705, -3.2079],
         [-1.7718,  0.2626,  0.1518,  0.3072, -0.2445],
         [ 1.5991,  0.6791, -0.9603, -0.7030,  0.3892]],

        [[ 0.1241,  1.2115, -0.3086, -0.0449, -0.1940],
         [-1.2796,  0.1195,  0.2883, -2.0981,  0.8086],
         [-0.3059,  1.4971,  0.0508, -0.6883, -0.2158]],

        [[ 0.8234,  0.0766, -0.1505, -0.4817,  0.8688],
         [-0.9505, -1.0981,  0.1937,  0.7871, -1.4882],
         [ 0.3619,  1.0449,  0.1715, -1.0768,  0.3769]],

        [[-0.1499, -0.7803, -1.6830,  0.8545,  0.4780],
         [ 1.1892,  0.3434,  0.9420,  1.0315,  1.4999],
         [-0.9968, -0.7962, -0.7610,  

### Tensor dimensions and rank
A tensor’s rank is its number of dimensions. A tensor that’s 0-dimensional is a scalar, 1-dimensional is a vector, 2-dimensional is a matrix, and so forth. In this example, we have a rank 3 tensor with dimensions $8\times3\times5$.

In [15]:
print(A.size())

torch.Size([8, 3, 5])


### Indexing
Tensors can be indexed using standard Python indexing syntax or list slicing syntax. The elements of a tensor can be accessed using the square brackets. The indices are in the order of dimensions, with the first dimension being the outermost. 

#### Standard indexing
The following example shows how to access the elements of a tensor.

<div align="center">

<img src="https://user-images.githubusercontent.com/30636259/206873403-f3f031ef-b4bf-4a70-b406-3e6b3b4d24a4.png" width="150">

</div>

In [16]:
print(A[0][0][0])

print(A[0,0,0])

tensor(0.6891)
tensor(0.6891)


#### List slicing
In addition to standard indexing, PyTorch provides list slicing syntax. The syntax is similar to NumPy’s, except that tensors can be sliced along multiple dimensions. In this example, we slice along the second dimension, namely the rows.

<div align="center">

<img src="https://user-images.githubusercontent.com/30636259/206873569-0e085349-e75a-4609-83aa-b1a75ad690a7.png" width="150">
<img src="https://user-images.githubusercontent.com/30636259/206873800-b6906d29-96d4-4b3e-9000-ed7358993ba0.png" width="150">

</div>

In [17]:
print(A[0,:,0])

print(A[0,0,:])

tensor([ 0.6891,  0.5856, -0.5576])
tensor([ 0.6891,  1.0174,  0.9346,  0.3579, -0.1727])


### Zero tensors
A tensor filled with zeros is useful for initializing weights in neural networks. The following example shows how to create a tensor of zeros with the same shape as another tensor.

In [18]:
B = torch.zeros_like(A)

print(B)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [19]:
C = torch.zeros((5,5))

print(C)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Dtype:
torch.float32


### Data types
Tensors can have different data types. The default data type is `torch.float32`. 

In [22]:
print(C.dtype)

D = torch.randint(2, (5,5))

print(D.dtype)

torch.float32
torch.int64


To set the default data type, use `torch.set_default_dtype`. The following example shows how to set the default data type to `torch.float32`.

In [25]:
torch.set_default_tensor_type('torch.FloatTensor')

E = torch.randn((5,5))
print(E.dtype)

torch.float32


## Device
In PyTorch, the device on which a tensor is stored is called the device. The device can be a CPU or a GPU. The following example shows how to check the device on which a tensor is stored.

In [26]:
print(C.device)

cpu


In [31]:
print(torch.cuda.is_available())

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

print(device)

False
cpu
